<?php

declare(strict_types=1);

namespace TInvest\Skill\Component\TInvest\OperationsService\Enum;

enum OperationTypeEnum: string
{
    case UNSPECIFIED = 'OPERATION_TYPE_UNSPECIFIED';
    case INPUT = 'OPERATION_TYPE_INPUT';
    case BOND_TAX = 'OPERATION_TYPE_BOND_TAX';
    case OUTPUT_SECURITIES = 'OPERATION_TYPE_OUTPUT_SECURITIES';
    case OVERNIGHT = 'OPERATION_TYPE_OVERNIGHT';
    case TAX = 'OPERATION_TYPE_TAX';
    case BOND_REPAYMENT_FULL = 'OPERATION_TYPE_BOND_REPAYMENT_FULL';
    case SELL_CARD = 'OPERATION_TYPE_SELL_CARD';
    case DIVIDEND_TAX = 'OPERATION_TYPE_DIVIDEND_TAX';
    case OUTPUT = 'OPERATION_TYPE_OUTPUT';
    case BOND_REPAYMENT = 'OPERATION_TYPE_BOND_REPAYMENT';
    case TAX_CORRECTION = 'OPERATION_TYPE_TAX_CORRECTION';
    case SERVICE_FEE = 'OPERATION_TYPE_SERVICE_FEE';
    case BENEFIT_TAX = 'OPERATION_TYPE_BENEFIT_TAX';
    case MARGIN_FEE = 'OPERATION_TYPE_MARGIN_FEE';
    case BUY = 'OPERATION_TYPE_BUY';
    case BUY_CARD = 'OPERATION_TYPE_BUY_CARD';
    case INPUT_SECURITIES = 'OPERATION_TYPE_INPUT_SECURITIES';
    case SELL_MARGIN = 'OPERATION_TYPE_SELL_MARGIN';
    case BROKER_FEE = 'OPERATION_TYPE_BROKER_FEE';
    case BUY_MARGIN = 'OPERATION_TYPE_BUY_MARGIN';
    case DIVIDEND = 'OPERATION_TYPE_DIVIDEND';
    case SELL = 'OPERATION_TYPE_SELL';
    case COUPON = 'OPERATION_TYPE_COUPON';
    case SUCCESS_FEE = 'OPERATION_TYPE_SUCCESS_FEE';
    case DIVIDEND_TRANSFER = 'OPERATION_TYPE_DIVIDEND_TRANSFER';
    case ACCRUING_VARMARGIN = 'OPERATION_TYPE_ACCRUING_VARMARGIN';
    case WRITING_OFF_VARMARGIN = 'OPERATION_TYPE_WRITING_OFF_VARMARGIN';
    case DELIVERY_BUY = 'OPERATION_TYPE_DELIVERY_BUY';
    case DELIVERY_SELL = 'OPERATION_TYPE_DELIVERY_SELL';
    case TRACK_MFEE = 'OPERATION_TYPE_TRACK_MFEE';
    case TRACK_PFEE = 'OPERATION_TYPE_TRACK_PFEE';
    case TAX_PROGRESSIVE = 'OPERATION_TYPE_TAX_PROGRESSIVE';
    case BOND_TAX_PROGRESSIVE = 'OPERATION_TYPE_BOND_TAX_PROGRESSIVE';
    case DIVIDEND_TAX_PROGRESSIVE = 'OPERATION_TYPE_DIVIDEND_TAX_PROGRESSIVE';
    case BENEFIT_TAX_PROGRESSIVE = 'OPERATION_TYPE_BENEFIT_TAX_PROGRESSIVE';
    case TAX_CORRECTION_PROGRESSIVE = 'OPERATION_TYPE_TAX_CORRECTION_PROGRESSIVE';
    case TAX_REPO_PROGRESSIVE = 'OPERATION_TYPE_TAX_REPO_PROGRESSIVE';
    case TAX_REPO = 'OPERATION_TYPE_TAX_REPO';
    case TAX_REPO_HOLD = 'OPERATION_TYPE_TAX_REPO_HOLD';
    case TAX_REPO_REFUND = 'OPERATION_TYPE_TAX_REPO_REFUND';
    case TAX_REPO_HOLD_PROGRESSIVE = 'OPERATION_TYPE_TAX_REPO_HOLD_PROGRESSIVE';
    case TAX_REPO_REFUND_PROGRESSIVE = 'OPERATION_TYPE_TAX_REPO_REFUND_PROGRESSIVE';
    case DIV_EXT = 'OPERATION_TYPE_DIV_EXT';
    case TAX_CORRECTION_COUPON = 'OPERATION_TYPE_TAX_CORRECTION_COUPON';
    case CASH_FEE = 'OPERATION_TYPE_CASH_FEE';
    case OUT_FEE = 'OPERATION_TYPE_OUT_FEE';
    case OUT_STAMP_DUTY = 'OPERATION_TYPE_OUT_STAMP_DUTY';
    case OUTPUT_SWIFT = 'OPERATION_TYPE_OUTPUT_SWIFT';
    case INPUT_SWIFT = 'OPERATION_TYPE_INPUT_SWIFT';
    case OUTPUT_ACQUIRING = 'OPERATION_TYPE_OUTPUT_ACQUIRING';
    case INPUT_ACQUIRING = 'OPERATION_TYPE_INPUT_ACQUIRING';
    case OUTPUT_PENALTY = 'OPERATION_TYPE_OUTPUT_PENALTY';
    case ADVICE_FEE = 'OPERATION_TYPE_ADVICE_FEE';
    case TRANS_IIS_BS = 'OPERATION_TYPE_TRANS_IIS_BS';
    case TRANS_BS_BS = 'OPERATION_TYPE_TRANS_BS_BS';
    case OUT_MULTI = 'OPERATION_TYPE_OUT_MULTI';
    case INP_MULTI = 'OPERATION_TYPE_INP_MULTI';
    case OVER_PLACEMENT = 'OPERATION_TYPE_OVER_PLACEMENT';
    case OVER_COM = 'OPERATION_TYPE_OVER_COM';
    case OVER_INCOME = 'OPERATION_TYPE_OVER_INCOME';
    case OPTION_EXPIRATION = 'OPERATION_TYPE_OPTION_EXPIRATION';
    case FUTURE_EXPIRATION = 'OPERATION_TYPE_FUTURE_EXPIRATION';
}
