parameters:
    tinvest.token: '%env(TINVEST_TOKEN)%'
    tinvest.account_id: '%env(TINVEST_ACCOUNT_ID)%'
    tinvest.base_url: '%env(TINVEST_BASE_URL)%'
    log.level: '%env(LOG_LEVEL)%'
    cache.directory: '%kernel.project_dir%/var/cache/t-invest-core'
    cache.ttl: 86400

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            string $token: '%tinvest.token%'
            string $accountId: '%tinvest.account_id%'
            string $baseUrl: '%tinvest.base_url%'

    TInvest\Core\:
        resource: '../src/*'
        exclude:
            - '../src/Component/TInvest/Shared/Dto/*'
            - '../src/Component/TInvest/*/Dto/*'
            - '../src/Component/TInvest/*/Enum/*'
            - '../src/Component/TInvest/*/Request/*'
            - '../src/Service/*/Dto/*'

    TInvest\Core\Command\:
        resource: '../src/Command/'
        tags: ['console.command']

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    Psr\Log\LoggerInterface:
        class: Monolog\Logger
        arguments:
            $name: 't-invest'
        calls:
            - pushHandler: ['@Monolog\Handler\StreamHandler']

    Monolog\Handler\StreamHandler:
        class: Monolog\Handler\StreamHandler
        arguments:
            $stream: '%kernel.project_dir%/var/log/t-invest-core/app.log'
            $level: '%log.level%'

    Symfony\Contracts\Cache\CacheInterface:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments:
            $namespace: 'tinvest_resolver'
            $defaultLifetime: '%cache.ttl%'
            $directory: '%cache.directory%'
